Frontend

FROM node:20 AS builder
WORKDIR /app
COPY frontend/package.json ./
RUN npm ci
COPY frontend/ .
RUN npm run build

stage-2
FROM nginx:stable-alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/build /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["NGINX", "-g", "daemon off,"]